# Generated by Django 5.0 on 2025-09-05 10:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("sms", "SMS Gateway"),
                            ("email", "Email Service"),
                            ("payment", "Payment Gateway"),
                            ("lms", "Learning Management System"),
                            ("ai", "AI Services"),
                            ("analytics", "Analytics Platform"),
                            ("storage", "Cloud Storage"),
                            ("video", "Video Conferencing"),
                            ("notification", "Push Notifications"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("provider", models.CharField(max_length=100)),
                ("version", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("maintenance", "Under Maintenance"),
                            ("deprecated", "Deprecated"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("config_schema", models.JSONField(default=dict)),
                ("default_config", models.JSONField(default=dict)),
                ("documentation_url", models.URLField(blank=True, null=True)),
                (
                    "support_contact",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DLTRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("entity_id", models.CharField(max_length=100, unique=True)),
                ("template_id", models.CharField(max_length=100)),
                ("header", models.CharField(max_length=6)),
                ("category", models.CharField(max_length=50)),
                ("content_type", models.CharField(max_length=50)),
                ("template_content", models.TextField()),
                ("variables", models.JSONField(default=list)),
                ("telecom_operator", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                ("messages_sent", models.IntegerField(default=0)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dlt_registrations",
                        to="schools.school",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchoolIntegration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enabled", "Enabled"),
                            ("disabled", "Disabled"),
                            ("error", "Error"),
                            ("configuring", "Configuring"),
                        ],
                        default="disabled",
                        max_length=20,
                    ),
                ),
                ("config", models.JSONField(default=dict)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("usage_count", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("last_error_time", models.DateTimeField(blank=True, null=True)),
                ("enabled_at", models.DateTimeField(blank=True, null=True)),
                ("disabled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="integrations.integration",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrations",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "unique_together": {("school", "integration")},
            },
        ),
    ]
